### ISSUE TITLE
Documentation should be auto generated where possible

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#111]
We should be able to auto generate the CLI and Schema documentation.

I think to do this we need:
-  To ensure our doc string has a full detailed description of each command.  This may mean that we need a more detailed version of the help.  Perhaps using a different CLI parser.
-  Fully document the API structure definitions and auto generate structures from the top level resource definitions.

**Comment by caseydavenport** [comment]
Is auto-generating the documentation really GA?

**Comment by robbrockbank** [comment]
Actually, given the number of resource types (not that many - auto generating is not really worth the additional effort) -  closing.
