### ISSUE TITLE
how to compatible data of etcdv2 and etcdv3

### ISSUE THREAD

**Issue by 1032120121** [projectcalico/libcalico-go#1118]
my data is in etcdv2, i hope using clientv3 to operate my old data in etcdv2, how do i do?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* libcalico-go version:
* Operating System and version:
* Link to your project (optional):

**Comment by tmjd** [comment]
I am not clear on the question you are asking. I am assuming you are wanting to upgrade your Calico installation from etcd v2 datastore to etcd v3. You should look at https://docs.projectcalico.org/v3.5/getting-started/kubernetes/upgrade/ to do that.
