### ISSUE TITLE
Go module support is incomplete

### ISSUE THREAD

**Issue by ymmt2005** [projectcalico/libcalico-go#1153]
Although libcalico-go has `go.mod` and its major version is tagged as `v3`,
the module name is still `github.com/projectcalico/libcalico-go` lacking
`/v3` suffix as required for [semantic import versioning](https://github.com/golang/go/wiki/Modules#why-must-major-version-numbers-appear-in-import-paths).

## Expected Behavior

`go get github.com/projectcalico/libcalico-go@v3.11.0-0.dev` should succeed.

## Current Behavior

It fails:
```console
$ go get github.com/projectcalico/libcalico-go@v3.11.0-0.dev
go: finding github.com/projectcalico/libcalico-go v3.11.0-0.dev
go: finding github.com/projectcalico/libcalico-go v3.11.0-0.dev
go get github.com/projectcalico/libcalico-go@v3.11.0-0.dev: github.com/projectcalico/libcalico-go@v3.11.0-0.dev: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3
```

## Possible Solution

Change module path to ` github.com/projectcalico/libcalico-go/v3`.

## Steps to Reproduce (for bugs)
See the current behavior.

## Your Environment

Go version 1.13.3

**Comment by caseydavenport** [comment]
Just to clarify, we don't cut releases of libcalico-go. It's not a publicly supported API right now, and we don't tag / release the repository. So, I think that this is out of scope.

If you really need to import it, I recommend just using a specific git hash for now. That is what we do for the upstream Calico repositories that make use of libcalico.
