### ISSUE TITLE
can't find the /bgp and /v1 in the etcd store

### ISSUE THREAD

**Issue by konghui** [projectcalico/libcalico-go#1167]
I read the confd template. It use many etcd keys like

```
prefix = "/calico"
keys = [
    "/v1/ipam/v4/pool",
    "/bgp/v1/host//NODENAME",
    "/staticroutes",
    "/rejectcidrs",
]
```

But when I use etcdctl show the keys I can't find any keys startwith like `/calico/v1` and `/calico/bgp`
but the confd was render the configuration success! It seem the keys is exists in the etcd.

I read the document [here](https://github.com/projectcalico/libcalico-go/blob/release-v3.7/docs/data-model.md) it show that `/calico/bgp` and `/calico/v1` is in the data model but I can't find it. Both use etcd v2 and v3 api.

I can only find the key what start with `/calico/resources` and `/calico/ipam/`

Is any thing I misunderstood? Thank you.

## Expected Behavior

Should find the key like `/calico/bgp` and `/calico/v1` 
## Current Behavior

Can't find `/calico/bgp` and `/calico/v1` 

## Your Environment

* libcalico-go version: 3.7.2
* etcd version: 3.3.13

**Comment by tmjd** [comment]
I think that document you linked to is the structure used in Calico v2.x, with the change to the v3 data model that document is only correct for the places where we still use the v1 data model, like in confd (I believe it is the syncer that converts our v3 data into the v1 data model).
We might need to just change the description of that document that it is the v1 data model and is not representative of how the data is written to etcd.

**Comment by konghui** [comment]
But I want to know why confd can use the key start with  `/calico/v1` and `/calico/bgp`  not exist in the etcd, but It can render the template success!  I remeber that confd is direct get the key from the etcd and replace it with value in the template. I read the source code it seems you don't change the logic in the confd.

**Comment by tmjd** [comment]
My understanding is that confd does not read from etcd directly but now only goes through libcalico-go which is responsible for a translation between the v1 and v3 data models. So the keys confd uses are still referencing the v1 data model and libcalico-go converts them to the v3 model.
@caseydavenport or @neiljerram, could one of you confirm my understanding here. Thanks

**Comment by neiljerram** [comment]
@tmjd Yes, that is right.

**Comment by neiljerram** [comment]
@konghui Our fork of confd has now diverged a lot from the upstream.  Whereas the upstream (kelseyhightower) confd performs a straightforward mapping from etcd content to the template files, I'm afraid our fork is now much more complex than that.

Do you have any more specific questions that we could help with?

**Comment by konghui** [comment]
Ok I get it .Thank you very much.
