### ISSUE TITLE
how can i user libcalico-go v3 with go mod

### ISSUE THREAD

**Issue by zhipengzuo** [projectcalico/libcalico-go#1198]
can't use libcalico-go with go mod
## Current Behavior

when i cmd " go get github.com/projectcalico/libcalico-go/lib/apis/v3"
shows "go get github.com/projectcalico/libcalico-go/lib/apis/v3: module github.com/projectcalico/libcalico-go@upgrade found (v1.7.3), but does not contain package github.com/projectcalico/libcalico-go/lib/apis/v3"

if i change the parameter "github.com/projectcalico/libcalico-go  v3.14.0-0.dev" in go.mod ,it also doesn't work," reading https://goproxy.cn/github.com/projectcalico/libcalico-go/@v/v3.14.0-0.dev.info: 404 Not Found"
how can i use v3?
## Your Environment

* libcalico-go version:
* Operating System and version:
* Link to your project (optional):

**Comment by rafaelvanoni** [comment]
@zhipengzuo I think you might be mixing Calico's internal API versioning (libcalico-go/lib/apis/v3) with our /release/ versions. I tried your `go get` command and it's working here.. maybe a connectivity issue on your end?

```
$ go get github.com/projectcalico/libcalico-go@v3.14.0-0.dev
go: finding github.com/projectcalico/libcalico-go v3.14.0-0.dev
go: downloading github.com/projectcalico/libcalico-go v0.0.0-20200303001954-8d098ee0dd61
go: extracting github.com/projectcalico/libcalico-go v0.0.0-20200303001954-8d098ee0dd61
package github.com/projectcalico/libcalico-go: build constraints exclude all Go files in /home/rafael/Work/go/pkg/mod/github.com/projectcalico/libcalico-go@v0.0.0-20200303001954-8d098ee0dd61
rafael@narwhal ~/Work/go/src/github.com/rafaelvanoni/goo
```

**Comment by zhipengzuo** [comment]
> go get github.com/projectcalico/libcalico-go@v3.14.0-0.dev

this also doesn't work.maybe the env is different.
go: cannot use path@version syntax in GOPATH mode

`go: finding github.com v3.14.0-0.dev
go: finding github.com/projectcalico v3.14.0-0.dev
go: finding github.com/projectcalico/libcalico-go v3.14.0-0.dev
go get github.com/projectcalico/libcalico-go@v3.14.0-0.dev: github.com/projectcalico/libcalico-go@v3.14.0-0.dev: reading https://goproxy.cn/github.com/projectcalico/libcalico-go/@v/v3.14.0-0.dev.info: 404 Not Found`

but i have solve this problem by using v1.7.2-0.20200225165413-26809aa675f6 .i will close this issue .thanks.
