### ISSUE TITLE
Add etcd data to node status command

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#121]
The alpha version of the node status command omitted some of the data that used to be included in the calicoctl-python status command.   We should re-instate this for GA.

**Comment by robbrockbank** [comment]
This is pending the completion of the config management

**Comment by caseydavenport** [comment]
What information is this exactly, just the BGP bind address?  Can we get that information from BIRD, and/or leave this out of the GA milestone?

**Comment by robbrockbank** [comment]
Actually, I don't think this is necessary.  The information that will be missing from the status command will be available through other means.  We can decide to add it later if we require - but I don't think we need to track that as it can be decided by trial.
