### ISSUE TITLE
IPAM blocks can overlap when IP Pool block size is modified

### ISSUE THREAD

**Issue by orange-llajeanne** [projectcalico/libcalico-go#1377]
## Expected Behavior
IPAM blocks generated by calico IPAM should not be able to overlap each other, since it enables situations where several pods have the same IP address.

## Current Behavior
In the situation described below, we have two IPAM blocks of different sizes that overlap each other, which ends up causing two pods from the same IP Pool to have the same IP address. 

## Possible Solution

The issue seems to come from `findUnclaimedBlock` at `lib/ipam/ipam_block_reader_writer.go:95`
``` golang
		blocks := randomBlockGenerator(pool, host)
		for subnet := blocks(); subnet != nil; subnet = blocks() {
			// Check if a block already exists for this subnet.
			log.Debugf("Getting block: %s", subnet.String())
			if _, ok := exists[subnet.String()]; !ok {
				log.Infof("Found free block: %+v", *subnet)
				return subnet, nil
			}
``` 

A block is considered free if there is no block with the same name (i.e IP+mask) already defined. This part could be adapted to check that the candidate block does not overlap with any existing block.

## Steps to Reproduce
Done on a kubernetes cluster with calico IPAM activated, and `AutoAllocateBlocks` enabled
1. Create an IP Pool
```yaml
spec:
  blockSize: 29
  cidr: 172.27.90.0/24
```
2. Create some pods in this pool: we now have newly created /29 IPAM blocks
```
+----------+-------------------+-----------+------------+------------+
| GROUPING |       CIDR        | IPS TOTAL | IPS IN USE |  IPS FREE  |
+----------+-------------------+-----------+------------+------------+
| IP Pool  | 172.27.90.0/24    |       256 | 5 (2%)     | 251 (98%)  |
| Block    | 172.27.90.144/29  |         8 | 4 (50%)    | 4 (50%)    |
| Block    | 172.27.90.32/29   |         8 | 1 (12%)    | 7 (88%)    |
+----------+-------------------+-----------+------------+------------+

``` 
3. Change IP Pool block size to another value
```yaml
spec:
  blockSize: 26
  cidr: 172.27.90.0/24
```
4. Create more pods in the same ip pool until a new /26 block is created with a range overlapping a /29 block
```
+----------+-------------------+-----------+------------+------------+
| GROUPING |       CIDR        | IPS TOTAL | IPS IN USE |  IPS FREE  |
+----------+-------------------+-----------+------------+------------+

| IP Pool  | 172.27.90.0/24    |       256 | 199 (78%)  | 57 (22%)   |
| Block    | 172.27.90.0/26    |        64 | 41 (64%)   | 23 (36%)   |
| Block    | 172.27.90.128/26  |        64 | 49 (77%)   | 15 (23%)   |
| Block    | 172.27.90.144/29  |         8 | 8 (100%)   | 0 (0%)     |
| Block    | 172.27.90.192/26  |        64 | 45 (70%)   | 19 (30%)   |
| Block    | 172.27.90.32/29   |         8 | 8 (100%)   | 0 (0%)     |
| Block    | 172.27.90.64/26   |        64 | 48 (75%)   | 16 (25%)   |
+----------+-------------------+-----------+------------+------------+
```
5. We now have pods in the same pool with the same IP address:
```
$ kubectl -n ns-one get po -o wide | grep 90.144
somedeploy-5c8fd9c494-cpdqr   1/1     Running   0          2m49s   172.27.90.144   node007   <none>           <none>
somedeploy-5c8fd9c494-q2hhj   1/1     Running   0          8m56s   172.27.90.144   node005   <none>           <none>
```

## Your Environment
Bare metal kubernetes cluster deployed with kubespray
Calico version: v3.14.1
ipam definition in cni configuration:
```
      "ipam": {
        "type": "calico-ipam",
        "assign_ipv4": "true",
        "ipv4_pools": ["172.27.88.0/24"]
      }
```

**Comment by mgleung** [comment]
Hey @orange-llajeanne , thanks for bringing this case to our attention. From my understanding, `calicoctl` should prevent you from changing the block size and CIDR for IP pools to prevent this from happening. I do not think we have a supported way of modifying the block size in already existing IP pools so if you wanted to make changes, you would need to remove the pods assigned to the block, delete the IP pool, and then recreate the IP pool with the desired specifications. Is there a specific reason that you need to edit the block size in an existing IP pool?

**Comment by orange-llajeanne** [comment]
Hello, thanks for your answer.

I actually do not have a use case in which I want to dynamically change the block size of an existing pool, i described this situation because this was the most direct way I could find to reproduce this issue. 
The situation I am in is the one you described (removing a pool and recreating it with a different size), but it creates the same issue.

However, by reading your comment about `calicoctl` doing checks when editing/deleting ip pools, I realized that this is where the problem comes from. In my situation I've got code that edits and deletes ip pools directly through the kubernetes `IPPool` custom resource, without using calicoctl. In this way I was unknowingly avoiding all the verification/cleaning logic contained in calicoctl, causing the mentionned issues.

Can you confirm that editing calico resources directly through the kubernetes client without using calicoctl is not supported / not recommended?

**Comment by mgleung** [comment]
@orange-llajeanne sorry for the late reply. Yeah, it's not recommended to edit the Calico resources directly through the k8s client. Not all of the resources need to be validated like IP pools, but there a few that do. You can generally see the checks done for each resource [here](https://github.com/projectcalico/libcalico-go/tree/master/lib/clientv3).

**Comment by caseydavenport** [comment]
@orange-llajeanne yes, that's not currently supported. Stay tuned though - I am working on a feature for Calico v3.19 which will enable this sort of workflow!

**Comment by lmm** [comment]
@orange-llajeanne I'm going to close this issue for now since I believe this is resolved.
