### ISSUE TITLE
CRD version should be v1

### ISSUE THREAD

**Issue by piepmatz** [projectcalico/libcalico-go#1428]
## Expected Behavior
In https://github.com/projectcalico/libcalico-go/blob/3503e05cfaa8b31701936084d78c9914c9446081/lib/apis/v3/register.go#L22 the exported `SchemeGroupVersion`'s `Version` field should be `v1`, similar to as it's done in https://github.com/projectcalico/libcalico-go/blob/3503e05cfaa8b31701936084d78c9914c9446081/lib/backend/k8s/k8s.go#L446

## Current Behavior
It's `v3`.

## Context
I am aware this repo is not intended as official golang lib, but in the end it's where the we get the CRDs and related stuff from. When building a scheme for the K8s client, being able to reuse the exported `SchemeGroupVersion` would be good.

**Comment by caseydavenport** [comment]
**Definitely, 100% do not use the CRDs or programming interfaces in this repository directly**. I can't stress that enough.

We're working on a supported API client for Calico here, which will be released with Calico v3.20: https://github.com/projectcalico/api

That said, you are correct that should be a "v1".

**Comment by caseydavenport** [comment]
https://github.com/projectcalico/libcalico-go/pull/1431
