### ISSUE TITLE
Should Source/Destination fields in the Rule be pointers?

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#147]
Currently these are non-pointers, but since they may contain completely empty values it feels like these should be pointers.

**Comment by caseydavenport** [comment]
I think the thing to think about here is "is there a distinction between the 0 value and the not specified value".

If src is not specified, is that behaviorally different from `src: {}`?

**Comment by caseydavenport** [comment]
Optional fields should probably all be pointers, so that they can be omitted.

**Comment by caseydavenport** [comment]
We really want to represent two things:
- Match all sources (don't care about source)
- Match some specified set of sources.

Doesn't sound like we _need_ a pointer for this.  Then again, the right semantics would probably be this:
- 1) `src: nil` - don't care about source
- 2) `src: {}` - match no sources
- 3) `src: {k:v, a:b}` match sources with k=v && a=b

#2 doesn't really make sense, so maybe the API could just validate it and error in that case?

**Comment by caseydavenport** [comment]
@robbrockbank @gunjan5 what do you think of the above?

**Comment by robbrockbank** [comment]
I don't think match no sources makes sense - we always have a source, so basically a nil source is not really required.  I'd be happy closing this out - accepting that a get may return an empty source or destination struct - and perhaps in the future updating the YAML marshaling to omit empty structs the same way it omits empty values.

**Comment by robbrockbank** [comment]
I'm not sure I feel that {} means match no sources.  That feels more like "we are matching on a source but don't care about any of the source parameters".   The parameters in the source map tighten up the match on the source so the fewer the parameters, the looser the match.  To me nil feels more like "match no sources" and therefore I think that pushes us towards not having nil as a valid value since it'll always be a negative match.

@caseydavenport I'm gonna close this out - accepting that we have {} returned on a get and eventually update the YAML marshaler to omit empty structs in the same way it omits empty values.  I believe this should be relatively easy if we fork the current golang marshaler (although we'd have to fork the yaml marshaler too :-( ).  I'll raise a separate low priority issue for that.  Please re-open if you disagree.
