### ISSUE TITLE
API scheme is not added to kubernetes client

### ISSUE THREAD

**Issue by tobiasgiese** [projectcalico/libcalico-go#1491]
If we add the calico scheme to the workload client, the scheme will not be added.
A `GlobalNetworkPolicy` apply will result in the following error

```
no kind is registered for the type v3.GlobalNetworkPolicy in scheme "pkg/runtime/scheme.go:100"
```

## Expected Behavior

The scheme should be added to the client.

## Current Behavior

Obviously, the scheme will not be added, because the `func addKnownTypes` returns only `nil`

https://github.com/projectcalico/libcalico-go/blob/e7396385abd4103da6afa2f9ec59b9bf97dd89de/lib/apis/v3/register.go#L42-L45

## Possible Solution

```go
func addKnownTypes(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(SchemeGroupVersion,
		&GlobalNetworkPolicy{},
		&GlobalNetworkPolicyList{},
		&GlobalNetworkSet{},
		&GlobalNetworkSetList{},
	)
	metav1.AddToGroupVersion(scheme, SchemeGroupVersion)
	return nil
}
```

## Steps to Reproduce (for bugs)

Usually, we're adding the scheme via

```go
_ = v3.AddToScheme(scheme)
```

After creating the client, the scheme is not added to it. Thus, we have to set the scheme manually via

```go
schemeGroupVersion := schema.GroupVersion{Group: "crd.projectcalico.org", Version: "v1"}
scheme.AddKnownTypes(schemeGroupVersion, &v3.GlobalNetworkPolicy{}, &v3.GlobalNetworkPolicyList{})
metav1.AddToGroupVersion(scheme, schemeGroupVersion)
```

## Your Environment

* libcalico-go version: `v3.9.0-0.dev` (and also the recent `master` branch)
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
I think the file in libcalico-go that you're referencing is dead at this point and should probably be removed.

You're likely looking for the API respository, which is where the API and clients are defined for public consumption: https://github.com/projectcalico/api/blob/master/pkg/apis/projectcalico/v3/register.go

**Comment by tobiasgiese** [comment]
Thanks for the clarification @caseydavenport :)
