### ISSUE TITLE
replace all the imports from `tigera/libcalico-go` to `projectcalico/libcalico-go`

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/libcalico-go#158]
- [ ] replace all the imports 
- [ ] replace any dependency in glide files
- [ ] replace references in docs 

`github.com/gunjan5/libcalico-go` has moved to `github.com/projectcalico/libcalico-go`

**Comment by gunjan5** [comment]
Not that this is not strictly required since github redirects all the requests to old URL to the new one forever AFAIK

**Comment by robbrockbank** [comment]
Fixed by #165
