### ISSUE TITLE
Use base net types for IP and CIDR fields in API

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#163]
We currently use anonymous fields in a struct to extend the net.IP etc. types.  I think we should use typedef to extend ... which means implementing certain key methods on the derived types (JSON marshaling and String() )

I think this is a clearer approach when accessing the methods on the original type since you need to explicitly recast to the original type to access the methods.  This makes it clear that the methods work on the original type not the derived type.

Motivation:  It fixes up the YAML output for types that are nil able, where we want to omit the field from the YAML if the value is nil.  If we subclass using a struct then the struct cannot be nil'ed without making it a pointer in the API.

**Comment by robbrockbank** [comment]
I think we should go one further and try and use the base net types ... and then somehow fixup the yaml marshaler and unmarshaler to handle arbitrary types.

**Comment by caseydavenport** [comment]
@robbrockbank I think we decided not to do this.
