### ISSUE TITLE
Rename fields in API and model

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#167]
There are a number of field renaming we need to do before GA:

WorkloadID -> Workload
OrchestratorID -> Orchestrator
Pool -> IPPool (pool -> ipPool)
Hostname -> Node

**Comment by caseydavenport** [comment]
Pool -> IPPool still needs to happen, but then can be closed.

**Comment by caseydavenport** [comment]
@gunjan5 can you fix up once the pool tests go through?

**Comment by caseydavenport** [comment]
@robbrockbank Could you explain the motivation behind renaming `Pool` to `IPPool`?  I don't really understand / remember why we want to do that.

**Comment by robbrockbank** [comment]
@caseydavenport:  simply that pool isn't particularly descriptive.... pool of what?   So ipPool was simply to tighten up the description.

**Comment by robbrockbank** [comment]
Rename the following:
libcalico-go:
lib/api/pool.go -> ippool.go
  Rename everything in here  Pool->IPPool   and   pool->ipPool
  (if you use the refactor feature it should rename within your codebase)

lib/backend/model/pool.go
  Bare minimum here is to rename the text in the String() methods to say IPPool instead of Pool


calicoctl

Update resources.go and resourcemgr

**Comment by gunjan5** [comment]
Pool -> IPPool merged in #240
