### ISSUE TITLE
Compile fails on 32 bit platform(ARM) validator.go

### ISSUE THREAD

**Issue by steve-wormley** [projectcalico/libcalico-go#173]
The line in validator.go fails to compile on 32 bit ARM.
156: 	return f >= 0 && f <= 4294967295

I replaced the magic constant with math.MaxInt32 and added a math import to my version.
I'm not sure what a more appropriate fix might be.

**Comment by robbrockbank** [comment]
I think the ASN needs to be a uint32 rather than just an int.   I'm actually fixing up the ASN field to make it a composite string/int so i'll make sure I specify the type of int correctly.

**Comment by robbrockbank** [comment]
@steve-wormley Could you retest - I think this may be fixed by explicitly using a uint32 for the ASN

**Comment by steve-wormley** [comment]
No errors on my end with a new compile.
