### ISSUE TITLE
Inconsistent use of pointers in backend API.

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico-go#179]
As discussed on Slack, the Syncer API returns KVPairs of the form: `KVPair{Key: k, Value: *v}`, where the rest of the API returns `*KVPair{Key: k, Value: v}`

This is causing me quite a bit of pain the work I'm doing at the moment.  

@fasaxc @robbrockbank leaving up to you guys to decide which you'd like it to be, but I'd like if we could make a decision with this _fast_ and the get on with it :)

I'm happy to take on whatever implementation work needs to be done.

**Comment by fasaxc** [comment]
@robbrockbank I think we settled on pointers and I think you have a WiP?
