### ISSUE TITLE
Update documentation to use new calicoctl commands

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#194]
- [ ]  Update all of the docs to use the latest commands
- [x]  Remove docs about non-docker networking docker containers
- [x]  Update our vagrant demos
- [x]  Move all documentation into the docs repo.

**Comment by robbrockbank** [comment]
@gunjan:  Do you think you could take this on to do the following:
-  Get the golang branch building cleanly
-  Make sure the resource definitions are accurate

**Comment by gunjan5** [comment]
@robbrockbank let me know if you want me to take over some of the commands docs work tomorrow.

**Comment by robbrockbank** [comment]
Closing issue and opening separate issues in calico repo
