### ISSUE TITLE
Validate should probably limit field sizes

### ISSUE THREAD

**Issue by lwr20** [projectcalico/libcalico-go#222]
As summary.  We should reject attempts to create really really long string values.  

Its unlikely that particularly long strings would be legitimate config - attempts to do so are more likely to be either bugs in automated config generation or done with malicious intent.

**Comment by lwr20** [comment]
Updating this to cover other limits in other fields.  e.g. numbers of labels, tags, etc, etc

**Comment by robbrockbank** [comment]
Best to get this in as soon as possible to prevent back compatibility issues.
