### ISSUE TITLE
Port numbers not validated correctly

### ISSUE THREAD

**Issue by lwr20** [projectcalico/libcalico-go#223]
calicoctl is accepting port ranges and lists containing port 0 and port 65536.

**Comment by gunjan5** [comment]
0 should be fine, I'll look into 65536

**Comment by lwr20** [comment]
Just for my education, why is 0 fine?

**Comment by gunjan5** [comment]
_after some discussion on slack_ 
we are going to validate to make sure we don't accept port 0 and 65536
