### ISSUE TITLE
link local IP pools should not be allowed

### ISSUE THREAD

**Issue by lwr20** [projectcalico/libcalico-go#224]
At present, calicoctl allows the configuration of a /0 pool - both for IPv4 and IPv6(!).  

There should probably be a maximum pool size.

**Comment by gunjan5** [comment]
after a quick chat with @matthewdupre, seems like `/0` might not be an issue, but policing something like pools that include 169.254.1.1 (or the IPv6 equivalent) would be nice to have, but it's not for the GA release.
