### ISSUE TITLE
Mismatched affinity representation with Python libcalico

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico-go#226]
As discussed here: https://github.com/projectcalico/calico-containers/issues/1194#issuecomment-256553868

Looks like the Go libcalico uses `hostAffinity: hostname` whereas the Python libcalico uses `affinity: host=hostname`.

This is pretty bad, and doubly so since the CNI IPAM plugin has been writing data in the former way since v1.4.0.  Changing this will likely have compatibility problems.

**Comment by caseydavenport** [comment]
From an offline discussion - for now we're going to write out _both_ keys to etcd, and prefer the `affinity: host=X` format when doing a read, falling back to the `hostAffinity` key if the other isn't present.

**Comment by gunjan5** [comment]
As discussed with @caseydavenport (offline) we're going to rename `hostAffinity` to `affinity` and store it in `affinity: host:X` format, and while reading (`Get` and `List`) check if the data is in `hostAffinity: X`, if so, convert it to `affinity: host:X` (in `compat.go`) to be compatible with existing deployments
