### ISSUE TITLE
Error handling and inefficient checking of pools

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#239]
```
// isConfiguredPool returns true if the given IPNet is a configured
// Calico pool, and false otherwise.
func (rw blockReaderWriter) isConfiguredPool(cidr cnet.IPNet) bool {
	allPools, _ := rw.client.IPPools().List(api.IPPoolMetadata{})
	for _, p := range allPools.Items {
		// Compare any enabled pools.
		if !p.Spec.Disabled && reflect.DeepEqual(p.Metadata.CIDR, cidr) {
			return true
		}
	}
	return false
}
```

-  We aren't catching the error from the List API, so de-referencing the Items in allPools will panic.
-  We shouldn't use List, we should just use Get - we know exactly when the pool CIDR is.

We should check other places where we are ignoring errors.

**Comment by caseydavenport** [comment]
@robbrockbank the CNI codebase has a test which checks for unhandled errors.  Worth adding to the CI for this repo too probably.

**Comment by gunjan5** [comment]
im working on this as part of #424
