### ISSUE TITLE
Tags should be metadata on profiles

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico-go#251]
tags should be part of the metadata for the API structs, _not_ part of the spec.  They're basically simpler labels.

As discussed with @lxpollitt

**Comment by caseydavenport** [comment]
Won't make this for 2.0.0-beta, but this should go into v2.0.0

**Comment by robbrockbank** [comment]
Yup funny was thinking that should be the case today....

**Comment by robbrockbank** [comment]
[ ] Update libcalico-go
[ ] Update libnetwork-plugin
[ ] Update CNI plugin
[ ] Update docs
[ ] Update calicoctl
