### ISSUE TITLE
Remove concept of tags

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico-go#253]
Eventually we want to deprecate tags for labels.  Not sure exact timeframe, but the idea is that any tag can really just be represented as a label.

e.g 

`projectcalico.org/tag: myProfileTag`

**Comment by robbrockbank** [comment]
I think we'd want the tag to be the key or a namespaced key, so maybe:

tag.projectcalico.org/myProfileTag: true

This allows you to apply a list of tags to an endpoint and allows you to use the `has("tag/myProfileTag")` selector.
