### ISSUE TITLE
Add some more evil IPAM tests

### ISSUE THREAD

**Issue by lwr20** [projectcalico/libcalico-go#261]
The tests for IPAM are OK, but I don't think they go far enough.  

Some ideas for tests to add:

- IP allocation: if I assign 4 IPs, release the 3rd, then request another, do I get the 3rd or the 5th returned?  I would suggest that we should get the 5th - to avoid races with other components (e.g. the orchestrator) in the situation where you allocate/release repeatedly and quickly.
- Allocate a bunch of IPs.   Then repeatedly release the oldest and allocate a new one.  Check that the block of allocated IPs remains contiguous, moves through the range of the pool, then is wrapped back to the beginning.
- As above, but with 2 pools. 
- Block allocation - similar to IP allocation, but for host blocks instead.
- a host has a block of addresses.  Allocate them all.  Release 1.  Allocate 1 - check it works.
- a host has a block of addresses.  Allocate them all.  Release N of them, spread through the range.  Request M of them (M<=N).  Check it succeeds without requesting a new block.  And that none of the returned IPs are already allocated.

**Comment by lwr20** [comment]
What should happen if a pool with outstanding allocations is deleted?

**Comment by lwr20** [comment]
- Add a pool.  Allocate an IP from it to a host.  Release that IP.  Create a new pool.   Delete the old pool.  Allocate another IP - check it comes from the new pool.

- As above, but swap the create new pool/delete old pool steps
 
- As above, but don't release the IP from the old pool before deleting it.

**Comment by lwr20** [comment]
- Add a pool of size N.  Attempt to allocate N+1 IPs from it - check it fails.
- Add a pool of size N.  Allocate N IPs from it, attempt to allocate one more - check it fails.
- Add 2 pools.  Allocate all IPs from them.  Release N of them, including some from both pools.  Attempt to allocate N IPs - check it succeeds, providing addresses from both pools.

**Comment by caseydavenport** [comment]
@gunjan5 don't we have the first two tests above?

**Comment by caseydavenport** [comment]
We've added quite a few IPAM tests recently as we've been developing new features in this area - e.g., configurable block sizes, IP pool node selection, etc. 

I think this should be closed - Reading through, I know from memory that we've already covered a large portion of these.
