### ISSUE TITLE
Should validate that rules don't mix IPv4/v6 CIDRs

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/libcalico-go#292]
Having a rule that matches on an IPv6 source and an IPv4 dest, for example, makes no sense and, as of 2.0.0 (https://github.com/projectcalico/felix/issues/1213), Felix ignores such rules.  (Previously, Felix did something counter-intuitive https://github.com/projectcalico/felix/issues/1212)

I think we should validate against that case in libcalico-go.

**Comment by robbrockbank** [comment]
Fixed by  #373
