### ISSUE TITLE
IPAM assignment uses random seed for affine block selection

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#294]
It should use a hash of the hostname to seed the random selection.  This way it avoids multiple affine blocks being allocated to a host if there are multiple concurrent IP requests at start of day (or when one affine block is full)

**Comment by gunjan5** [comment]
https://github.com/projectcalico/libcalico-go/blob/master/lib/client/ipam_block_reader_writer.go#L344

**Comment by caseydavenport** [comment]
We should do this for v1.0.0.

@heschlie care to address this one? Should be a quick fix.
