### ISSUE TITLE
Unable to Delete Namespaces due to k8s TPR

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico-go#297]
```
E1209 15:53:27.737903       1 errors.go:63] apiserver received an error that is not an unversioned.Status: no kind "DeleteOptions" is registered for version "projectcalico.org/v1"
```

Deleting a Namespace tries to delete all resources in that ns, but apparently there is no delete options registered which is causing the ns to hang in `Terminating` state.

This occurs when using the Kubernetes datastore driver (i.e DATASTORE_TYPE=kubernetes) because it uses a ThirdPartyResource to store global config (https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/k8s/k8s.go#L169).  It does not affect deployments using etcd as the datastore.

Workaround is to delete the TPR (this means that `calicoctl config` won't work).

```
kubectl delete thirdpartyresource global-config.projectcalico.org
```

**Comment by caseydavenport** [comment]
I've so far been unable to reproduce using Calico v2.0.0-rc2 + Kubernetes v1.4.0 and k8s v1.4.5.

Workaround is to delete the TPR via `kubectl delete`.  Side effect is that `calicoctl config` commands will no longer work.

**Comment by caseydavenport** [comment]
See this upstream issue as well: https://github.com/kubernetes/kubernetes/issues/37278

**Comment by sysradium** [comment]
However it seems that the thirdparty resource isn't needed on k8s 1.5?

**Comment by caseydavenport** [comment]
@sysradium When Calico is using k8s instead of etcd as it's datastore, it will create TPRs to store various pieces of data.  In this case, there is a TPR that Calico needs.

If you're using etcd + Calico, then this issue doesn't apply.

**Comment by hectorj2f** [comment]
@caseydavenport we see this problem with other TPRs, it has nothing to do with calico itself. If this helps you ;).

**Comment by sysradium** [comment]
@hectorj2f yes, I know that. But since it is not fixed yet I am trying to find a workaround :)

@caseydavenport thanks. But now K8S has networkpolicies out of the box - there is a `/apis/extensions/v1beta1/networkpolicies` where you can store the policies for calico to use.

So I am not sure if the `network-policy.net.alpha.kubernetes.io` third party resource is still needed in the recent versions of calico. It isn't mentioned in the Calico docs :)

**Comment by caseydavenport** [comment]
> So I am not sure if the network-policy.net.alpha.kubernetes.io third party resource is still needed in the recent versions of calico

@sysradium Correct.  This issue isn't referring to the NetworkPolicy alpha TPR, rather the TPRs created by Calico itself for storing global configuration.  See here: https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/k8s/k8s.go#L169

I updated the description to make that more clear :)

@hectorj2f Yeah, I've seen it with other TPRs as well.  At this point I don't think there's anything that Calico is doing wrong, it's just an upstream bug that happens to affect us, so I'll close this issue.
