### ISSUE TITLE
Need a "ping" API to check if a backend is reachable from a host

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/libcalico-go#306]
Also to check if a user has read or read/write permissions

Background: right now we have to do a Get on a node to see if it is "connected" to the backend, having a `IsConnected(hostname)` or something similar to check if datastore is reachable would help a lot. 

CC @robbrockbank

**Comment by djosborne** [comment]
Specifically, this is so `startup.go` can enact the `$WAIT_FOR_DATASTORE` flag

**Comment by caseydavenport** [comment]
We have a hook `EnsureInitialized` which might do the trick.  Would just need to be updated to say "returns an error if it can't connect to the datastore"

**Comment by gunjan5** [comment]
So my understanding for this issue is to implement `EnsureInitialized` for `etcdv2` backend which is a noop for now

**Comment by gunjan5** [comment]
@caseydavenport seems like k8s backend has `EnsureInitialized()` implemented now. If that's the case, can we close this issue?

**Comment by caseydavenport** [comment]
@gunjan5 it's the etcd backend that we were waiting for.  k8s has always had EnsureInitialized.

I think this is fixed in the startup.go stuff that @robbrockbank was working on, so we can close thi.
