### ISSUE TITLE
calicoctl link is broken

### ISSUE THREAD

**Issue by DreadPirateShawn** [projectcalico/libcalico-go#310]
The main page of this repo says:

> If you are looking for the golang version of calicoctl it is in the process of moving and can be found in our calico-containers repo / golang branch.

Hyperlink goes here: https://github.com/projectcalico/calico-containers/tree/golang

However, that link is dead -- presumably this should be https://github.com/projectcalico/calico-containers/tree/master/calicoctl or similar.

**Comment by gunjan5** [comment]
Thanks @DreadPirateShawn for spotting this! :) 
I will fix it
