### ISSUE TITLE
Improve logging in Kubernetes datastore driver

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico-go#333]
Logging is a bit weak in this area.

We need to do the following:
- [ ] Use context loggers where appropriate
- [ ] Ensure standardized log format (matches Felix)
- [x] Make sure Error logs are errors, and warning logs are warnings (and other log levels are appropriate)
- [ ] Add in debug logging in a number of places that don't have it.

**Comment by fasaxc** [comment]
- [ ] Add context to logs around resync; which watch was it that failed?
