### ISSUE TITLE
Force a resync if too many Syncer failures

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/libcalico-go#351]
After discussing #343 with @robbrockbank, we think we should be more defensive and break out of the watch loop if we hit too many failures.

**Comment by caseydavenport** [comment]
@fasaxc could you provide a bit more information for this? What is it trying to solve? What sorts of failures does this cover?

**Comment by fasaxc** [comment]
Work in progress on this PR but I haven't had time to finish off the UTs: https://github.com/projectcalico/libcalico-go/pull/380
