### ISSUE TITLE
Client example in the docs is broken

### ISSUE THREAD

**Issue by mdirkse** [projectcalico/libcalico-go#359]
The [client package docs](https://godoc.org/github.com/projectcalico/libcalico-go/lib/client#Client) contain an example that tells you to initialize a Calico client in the following way:
```go
config := api.ClientConfig{}
client := New(&config)
```
However, this doesn't actually work as the ClientConfig struct [does not seem to exist](https://github.com/projectcalico/libcalico-go/search?utf8=%E2%9C%93&q=ClientConfig).

The way I ended up making it work was by using the following code:
```go
config := api.NewCalicoAPIConfig()
config.Spec.DatastoreType = api.EtcdV2
config.Spec.EtcdEndpoints = "http://localhost:2379"
client, err := client.New(*config)
```

Not sure if that's "the" way to do it though.

**Comment by gunjan5** [comment]
@mdirkse we've updated the GoDoc and added a new function to initialize the client with default settings (in PR https://github.com/projectcalico/libcalico-go/issues/366) . 
Thanks for raising this issue! Let us know if it doesn't address your question.
