### ISSUE TITLE
Include revision metadata in northbound objects to allow for atomic operations

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#36]
The backend client KVPairs include revision data which allows atomic operations on objects to be performed.  The revision data is not passed up to the northbound resource definitions and so it is currently not possible to perform atomic operations using the northbound API.

**Comment by robbrockbank** [comment]
Matt - I think you were at least thinking about this from your work in libcalico.

**Comment by robbrockbank** [comment]
This is not required for GA, but will likely be required further out.

**Comment by caseydavenport** [comment]
@heschlie this might be a good ramp-up candidate for you on libcalico-go.

@robbrockbank is it OK is @heschlie takes this? Is this somewhere in your plan?

**Comment by caseydavenport** [comment]
@gunjan5 you did a little bit of work on this - is this closed? Is there more to do here?

Looks like maybe only some of the objects have revision data passed through?

**Comment by gunjan5** [comment]
@caseydavenport yeah it's only exposed for WEP at the moment. @robbrockbank has a branch for work on completely restructuring libcalico-go which will have this included (maybe not by the same means)

**Comment by caseydavenport** [comment]
Will add these as needed by a particular feature.
