### ISSUE TITLE
Cannot build in the clean environment

### ISSUE THREAD

**Issue by lijohnso** [projectcalico/libcalico-go#377]
Since the k8s.io/client-go has changed a lot, i met issue while building the codes. 
firstly, it says that the metav1 and schema is not found in client-go, i found the folders are moved to 
k8s.io/apimachinery/pkg/runtime/schema and k8s.io/apimachinery/pkg/apis/meta/v1. 
I changed the import package to the new path, now it shows another error:
lib/backend/k8s/resources/ippools.go:68: cannot use &res (type *thirdparty.IpPool) as type runtime.Object in argument to req.Do().Into:
        *thirdparty.IpPool does not implement runtime.Object (wrong type for GetObjectKind method)
                have GetObjectKind() schema.ObjectKind
                want GetObjectKind() unversioned.ObjectKind

**Comment by caseydavenport** [comment]
@lijohnso hm, sounds like client-go has had some breaking changes.

Any reason you need to update the vendored version right now? We should definitely tackle this so we don't fall out of date, but would keeping the pin in `glide.yaml` at `243d8a9cb66a51ad8676157f79e71033b4014a2a` work for you?

**Comment by lijohnso** [comment]
@caseydavenport Hi, thanks for reply, no special requirement, just because i'm trying to build it with newly setup machine, it uses the master branch of the client-go. So the issue occurs. I will try to use the same commit id and try again.

**Comment by lijohnso** [comment]
@caseydavenport  Hi, sorry to trouble again, i tried to use the commit id you sent, the issue is gone now, but i met another issue, the netlink and cni commit id(07a8a28637e97b22eb8dfe710eeae1344f69d16e) doesn't match. The error looks like:

utils/network.go:78: cannot use contVeth (type "github.com/vishvananda/netlink".Link) as type "github.com/containernetworking/cni/vendor/github.com/vishvananda/netlink".Link in argument to ip.AddDefaultRoute:
        "github.com/vishvananda/netlink".Link does not implement "github.com/containernetworking/cni/vendor/github.com/vishvananda/netlink".Link (wrong type for Attrs method)
                have Attrs() *"github.com/vishvananda/netlink".LinkAttrs
                want Attrs() *"github.com/containernetworking/cni/vendor/github.com/vishvananda/netlink".LinkAttrs
utils/network.go:108: cannot use contVeth (type "github.com/vishvananda/netlink".Link) as type "github.com/containernetworking/cni/vendor/github.com/vishvananda/netlink".Link in argument to ip.AddRoute:
        "github.com/vishvananda/netlink".Link does not implement "github.com/containernetworking/cni/vendor/github.com/vishvananda/netlink".Link (wrong type for Attrs method)
                have Attrs() *"github.com/vishvananda/netlink".LinkAttrs
                want Attrs() *"github.com/containernetworking/cni/vendor/github.com/vishvananda/netlink".LinkAttrs

**Comment by caseydavenport** [comment]
@lijohnso that also sounds like a mismatched vendor version - how have you installed the various dependencies listed in glide.yaml, and how are you building libcalico?

A using `glide install` should install the right versions.

**Comment by zwpaper** [comment]
@caseydavenport Hi, I was trying to build the calico cni plugin, I got exactly the same error with lijohnso, and I try `glide install`, It doesn't work, the error still there.

**Comment by gunjan5** [comment]
@zwpaper are you using `make vendor` target? It's containerized so it should _produce_ the same result. I just tried it with master cni-plugin and it worked

**Comment by zwpaper** [comment]
I am sorry for my mistaken build cmd, I was using a `go build` to build the `calico-ipam.go`, and it does not work, later, I found out the `make binary`, this works, but can I ask why should I use the `make binary`, but `go build` not working?

**Comment by gunjan5** [comment]
@zwpaper internally `make binary` is also doing `go build` see: https://github.com/projectcalico/cni-plugin/blob/master/Makefile#L87-L88 it also passes `ldflags`, etc. in addition to `go build`

**Comment by zwpaper** [comment]
@gunjan5 OK, thank you! I will read the `makefile` about the detail.

**Comment by tmjd** [comment]
@zwpaper and @lijohnso Are the issues you reported still causing problems?

**Comment by zwpaper** [comment]
@tmjd I can now use the `make binary` to build the project, so there is not problems for me, Thank you.

**Comment by tmjd** [comment]
I'm going to close this issue for now.  @lijohnso if you are till having troubles building then of course feel free to reopen this issue or create a new one if appropriate.  You can also checkout https://www.projectcalico.org/community for other support channels too.
