### ISSUE TITLE
Using deprecated clientSet.Extensions in Syncer in KDD

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#400]

**Comment by caseydavenport** [comment]
@robbrockbank could you point to the deprecation notice / lines we're using this / add some description to this issue?

**Comment by fasaxc** [comment]
Goglang was flagging this up to me too:
```
// Deprecated: Extensions retrieves the default version of ExtensionsClient.
// Please explicitly pick a version.
```

**Comment by caseydavenport** [comment]
This should be really easy so adding to 2.5

**Comment by bcreane** [comment]
we're no longer using the deprecated extensions api (libcalico-go extensions)
