### ISSUE TITLE
Need to write e2e tests of resource management

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#41]
It would be a good idea to write some end to end tests that could test data in -> data written to etcd.

- [x] Pool #188 
- [x] Profile #210 
- [x] Policy #189 
- [x] BGPPeer #208 
- [x] HostEndpoint #201 
- [x] WorkloadEnfpoint #209

**Comment by caseydavenport** [comment]
@gunjan5 this is what you're working on for the next few days, yeah? I'm assigning to you.

**Comment by gunjan5** [comment]
all FVs (also called e2e in most places) are merged
