### ISSUE TITLE
Need to write UTs

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#42]

**Comment by caseydavenport** [comment]
@gunjan5 could you update the description of this issue to include the set of UTs you think we need for GA, checking off the ones you've already completed?

**Comment by gunjan5** [comment]
I think the UTs would only include `randomblock_test` and `ipam_test` which tests `AutoAssign`, `AssignIP`, `ReleaseIPs`, `ClaimAffinity` and `ReleaseAffinity` UTs, rest of `libcalico` stuff should be covered by the FVs in #41
