### ISSUE TITLE
KDD may be resyncing too much

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/libcalico-go#433]
It seems the k8s times out an inactive watch after about 30 minutes.  When one of KDD's watches times out, it does a full resync, which can be very expensive at high scale.  This introduces a lot of unnecessary latency if the watch that timed out could be restarted or only that resource resynced.

## Expected Behavior
If a watch for a low-traffic resource times out, reestablish it without doing full resync.

## Current Behavior
Full resync including expensive pod resync.

## Possible Solution
Run each watcher in own goroutine, reestablish watch without disturbing others?

**Comment by robbrockbank** [comment]
@caseydavenport:  I've been thinking about this a little with the KDD routing stuff - since I wanted to use that opportunity to refactor the various different ways we do stuff.  This could relatively easily be designed in.

**Comment by caseydavenport** [comment]
@robbrockbank I was planning on looking at this later today or tomorrow.  Maybe we could chat if you've got some time.
