### ISSUE TITLE
Improve libcalico logging levels

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#45]
Most of the logging in libcalico is V2 level glog.  Need to revisit the logging levels to ensure logging is not quite so verbose.

Perhaps consider a different logging package.

If we stick with glog, then perhaps follow k8s logging level guide:

https://github.com/kubernetes/kubernetes/blob/master/docs/devel/logging.md

**Comment by caseydavenport** [comment]
I think we've moved away from glog in favor of logrus, so this should include making sure we've standardized on that.

**Comment by robbrockbank** [comment]
We already sue logrus now - but the log levels do need sorting out.

Not particularly important for the release of calicoctl since logging is disabled by default.  Where required by Felix, the logging levels have already been sorted out.  This is therefore low priority.
