### ISSUE TITLE
IP object can't be stringified if it's nil

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico-go#452]
## Expected Behavior

Stringifying a Calico net.IP should work when the IP is nil, and print `<nil>`

## Context

From this comment: https://github.com/projectcalico/libcalico-go/pull/448#issuecomment-30775714

**Comment by fasaxc** [comment]
I tried and tried to get this to work.  I don't think it's possible without restructuring the way we do the IP type.

**Comment by caseydavenport** [comment]
Closing as wontfix for now
