### ISSUE TITLE
Support multiple YAML documents separated by ---

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#47]
Customer request to support multiple YAML documents with `---` document separators.
(check that it is valid YAML though)

e.g.

```

---
apiVersion: v1
kind: hostEndpoint
metadata:
   ....

---
apiVersion: v1
kind: hostEndpoint
metadata:
   ...
```

**Comment by robbrockbank** [comment]
This will be a tricky one to implement as it'll require some changes to the YAML parser.

**Comment by tomdee** [comment]
Isn't this just part of the yaml spec (i.e. multiple documents?) http://yaml.org/spec/1.2/spec.html#id2800132
