### ISSUE TITLE
KDD doesn’t pass node IP information to Felix during resync

### ISSUE THREAD

**Issue by bcreane** [projectcalico/libcalico-go#485]
Specific to KDD, when calico-node is restarted, we see a data plane connectivity issue that lasts 5-12 seconds. This issue is seen in both v2.3 and v2.4.

## Expected Behavior
Restarting calico-node should not result in data plane disruption.

## Current Behavior
Running intra-node iperf session, I observe a 5-12 second break in connectivity.

## Steps to Reproduce (for bugs)

1. deploy k8s cluster with KDD backend
2. spin up iperf on two different nodes: `kubectl run iperf --image=phlak/iperf --replicas=2`
3. run iperf: `kubectl exec -it iperf-X -n default sh`, then: `# iperf -c 192.168.X.X -t 3600 -i 1`
4. kill one of the calico-nodes where iperf is running: `kubectl delete pod -n kube-system calico-node-XX`

See https://github.com/projectcalico/calicoctl/issues/1419 for related debugging info.

## Your Environment

* libcalico-go version:
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Tracked this down to the KDD syncer not sending through Node IPs to Felix during its initial snapshot - [see here](https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/k8s/syncer.go#L781).

Felix thus removes the node IPs from the "all-ips" ipset and re-populates them as it receives subsequent watch updates.

**Comment by bcreane** [comment]
A DROP rule was getting hit during calico-node restart, observed via (on each node):
    `sudo watch -d -c -n 0.1 "iptables-save -c -t filter | grep DROP"`

Subsequently watched the associated ipset change for a brief moment (on each node):
    `sudo watch -d -n 0.1 "ipset list cali4-all-hosts"`
