### ISSUE TITLE
Restore client-go Extensions functionality

### ISSUE THREAD

**Issue by bcreane** [projectcalico/libcalico-go#525]
## Expected Behavior
Calico should use client-go rather than libcalico-go's extension api.

## Current Behavior
As part of https://github.com/projectcalico/libcalico-go/pull/520, we bypassed Client-go's extensions api because there was no released client-go version that supports k8s v1.8.0.
The changes span multiple repos, including: k8s-policy, and libcalico-go. 

## Possible Solution
Remove the use of `BuildExtensionsClientV1()` and associated package from all clients and replace with appropriate client-go library.

## Your Environment

* libcalico-go version: 6d51f61415fde119b39a0350e5e0d36d882a57fe
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
This is fixed in master.
