### ISSUE TITLE
Improve Kubernetes syncer creating watchers

### ISSUE THREAD

**Issue by heschlie** [projectcalico/libcalico-go#538]
In the Kubernetes syncer we currently create the watchers before we fall into listening for events in the `kubeSyncer.ReadFromKubernetesAPI()` loop.  This logic works well most of the time but if you are missing a resource (like the GlobalNetworkPolicy CRD) then we never hit the `select` that lets us pull from the channels.

If we were to switch each watcher creation to a goroutine we could start grabbing events from the channels that were successfully opened even if we are not able to create all of the watchers. This was suggested in #501.

## Expected Behavior
If we fail to watch one resource it should not block us from watching the rest or starting to listen for events.

## Current Behavior

We short circuit the loop, resync, and retry watching all resources.

## Possible Solution

Use goroutines for creating watchers.

## Steps to Reproduce (for bugs)

1. Spin up cluster with Kubernetes 1.7+
2. Apply Calico Kubernetes datastore manifest
3. Delete GlobalNetworkPolicy CRD
4. Observe in logs we never start receiving events in logs

## Your Environment

* libcalico-go version: v1.6.1
* Operating System and version: Vagrant CoreOS
* Link to your project (optional):

**Comment by robbrockbank** [comment]
The v3.0-integration branch has a SyncerWatcher implementation that does just that...

**Comment by caseydavenport** [comment]
Fixed in v3.0 alpha.
