### ISSUE TITLE
Getting a WEP that does not exist should return an error

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/libcalico-go#640]
Getting a wep that does not exist should return an error.

## Current Behavior

```
    Got error: <nil>
    Expected
        <bool>: false
    to be true
```

## Steps to Reproduce (for bugs)

```
_, err = calicoClient.WorkloadEndpoints().Get(context.Background(), "default", "made-up-wep-name", options.GetOptions{})
Expect(err).NotTo(BeNil())
```

## Your Environment

* libcalico-go version:
* Operating System and version:
* Link to your project (optional):

**Comment by heschlie** [comment]
@ozdanborne Do you recall what versions you were seeing this against, I popped that test into the WEP UTs and it passed, and I don't see us trimming any errors out in the plumbing for WEP gets.

I'm testing against the current latest master (e8d93a6ef128b79fddc09e5f673386c46cab6d10).
