### ISSUE TITLE
Only validate the fields required for a particular request type (e.g. create, delete, get)

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#65]
Currently we have a lot of validation fields marked as "omitempty" when we really should be validating them

I think we need to do a few things:
-  For create, update, apply validate the Spec (and honor required indicator)
-  For create, update, apply, delete validate the Metadata (And honor the required indicator)

otherwise
-  Validate Spec and/or Metadata but allow fields to be empty (in which case they won't be validated)

**Comment by caseydavenport** [comment]
I'm not sure what actually needs to be done for this task - is this just adding more fields to `validator.go`?

**Comment by robbrockbank** [comment]
At the moment we always validate the full contents of the YAML data.    This means, at the moment, you can't just feed in a list of YAML with empty specs to delete a set of objects (you really only need the metadata) -- because the spec data is validated.

When deleting/getting/listing it is not necessary to validate the Spec data since that is not actually used in the request.

We should limit exactly what is validated based on the type of request.

I'm considering this low priority though and not required for GA.
