### ISSUE TITLE
Allow some modification of WorkloadEndpoints via calicoctl

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico-go#67]
https://github.com/tigera/libcalico-go/blob/master/calicoctl/commands/delete.go#L121

Means users can't delete workload endpoints.  

As per this feature request: https://github.com/projectcalico/calico-containers/issues/1034

I think it makes sense to allow people to clean up orphaned endpoints.  We probably don't need Create / Apply / Update actions though.

**Comment by robbrockbank** [comment]
Fixed by  #162
