### ISSUE TITLE
Addresses are allocated from disabled ipPools

### ISSUE THREAD

**Issue by aaronbbrown** [projectcalico/libcalico-go#689]
When the `spec.disabled` parameter in an ipPool is set to `true`, IP addresses are still allocated from the disabled pool when using `calico-ipam`.

## Expected Behavior

Intuitively, I would expect that after disabling an ipPool w/ `calicoctl apply -f ippool.yaml` (using the yaml below), IP addresses will no longer be allocated from the pool that has been disabled.  If this is not an accurate assessment, the documentation should be updated to indicate that the disabled flag only applies to the allocation of new affine blocks.

`ippool.yaml`:

```yaml
apiVersion: v1
kind: ipPool
metadata:
  cidr: 10.125.128.0/17
spec:
  ipip:
    enabled: true
  nat-outgoing: true
  disabled: true
```

## Current Behavior

From looking at the [`autoAssign` method in `lib/client/ipam.go`](https://github.com/projectcalico/libcalico-go/blob/5cabf71a9999834727d83036e986836084e0a13a/lib/client/ipam.go#L158-L287), if a host has already been assigned a /26 block (is that what is called an "affine block?") from the disabled ipPool and the block appears first (lexographically, maybe?) in etcd and there are available IP addresses in the /26, then an IP will be allocated from the disabled pool **without ever checking if the pool is disabled**. It seems like the only place [`spec.Disabled` is checked](https://github.com/projectcalico/libcalico-go/blob/5cabf71a9999834727d83036e986836084e0a13a/lib/client/ipam.go#L254-L256) is after a number of different assignment/allocation attempts have failed.

## Steps to Reproduce (for bugs)
1. Allocate an ipPool
2. Allocate a second ipPool
3. Disable the first ipPool, by setting `spec.disabled: true`
4. Request new IPs by creating new Pods: IPs will come from both pools :point_up:

## Context

We ran into this at GitHub after discovering that the wrong Pod CIDR was allocated to a production Kubernetes cluster and we needed to migrate to a new Pod CIDR without downtime. Our plan was to add a new (correct) ipPool, disable the old (errant) ipPool, then remove the old ipPool once all Pods had IPs from the correct CIDR. The idea was that Pods that had IPs from the disabled pool would still be routable, but no *new* IPs would be allocated from the disabled pool.

## Your Environment
* libcalico-go version: v1.7.1 ([via](https://github.com/projectcalico/cni-plugin/blob/c7960b84977259c8185c8eff5794ce3cfb6d073e/glide.yaml#L20-L21) cni-plugin v1.11.0)
* Operating System and version: Debian Jessie
* Kubernetes v1.6.7 using the following CNI config:

```
{
    "name": "k8s-pod-network",
    "cniVersion": "0.1.0",
    "type": "calico",
    "etcd_endpoints": "http://10.1.1.1:2379,http://10.1.1.2:2379,http://10.1.1.3:2379",
    "etcd_key_file": "",
    "etcd_cert_file": "",
    "etcd_ca_cert_file": "",
    "log_level": "debug",
    "ipam": {
        "type": "calico-ipam"
    },
    "policy": {
        "type": "k8s",
        "k8s_api_root": "https://10.2.1.1:443",
        "k8s_auth_token": SOMETOKEN
    },
    "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
    }
}
```

Thanks for taking a look!  I'm happy to add more context or help w/ contributing a fix.

**Comment by aaronbbrown** [comment]
Hey, I suspect you folks are getting ready for KubeCon and pretty busy, but I'd ❤️  if I could get a 👍 / 👎 on whether this behavior is intentional/expected or if this might be a bug. Thanks!

**Comment by caseydavenport** [comment]
@aaronbbrown yes, sorry for taking so long for responding here! 

I think this is unintentional - @robbrockbank do you agree?

**Comment by tmjd** [comment]
I added a test here https://github.com/tmjd/cni-plugin/commit/e302124145704ea2f17094062ad347f5f9d3955a, that shows the unexpected behavior I believe.

**Comment by joewilliams** [comment]
@tmjd thanks! I am having some issues getting tests running on my local but that does indeed look like it replicates the behavior we were seeing.

**Comment by aaronbbrown** [comment]
Hey @tmjd thanks 🙇 for adding that test.  Sure looks like what we were bumping into.

**Comment by joewilliams** [comment]
Thanks everyone! 🎉
