### ISSUE TITLE
Switch to networking.k8s.io instead of extensions

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico-go#704]
https://github.com/kubernetes/kubernetes/pull/56425

Extensions is deprecated in v1.9. We should swap over to the networking.k8s.io API before this happens.

Will require changes in libcalico, kube-controllers, and in our RBAC manifests.

**Comment by bcreane** [comment]
@caseydavenport - any remaining work on this issue, or okay to close?

**Comment by caseydavenport** [comment]
I think we're good to go on this one!

Thanks @bcreane for doing this :)
