### ISSUE TITLE
FelixConfig loses precision vs Felix's config parser

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/libcalico-go#712]
Felix supports fractional seconds/millis for `time.Duration` fields but those have been mapped through to `*int`s on the FelixConfig type.

## Expected Behavior

Should be able to set a fractional number of seconds for, say `IptablesPostWriteCheckIntervalSecs`, but it's typed as an int.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* libcalico-go version:
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Should probably change those config options to support `*time.Duration`
