### ISSUE TITLE
k8s_test.go tries to defer It() blocks and assumes test ordering

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/libcalico-go#716]
Code reading k8s_test.go, it's trying to do things like deferring `It()` calls, which makes no sense given ginkgo's approach to collecting specs. 

The correct way to run teardown code is in an AfterEach or AfterSuite block.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* libcalico-go version:
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@fasaxc what is the impact of this? Could it result in flaky tests?

Could you assign a priority to this issue?

**Comment by fasaxc** [comment]
Depends how we run ginkgo.  If ginkgo is configured to randomise the order of these specs then the deferred `It()` may run out-of-order.  If not, then the test will do what the developer expected (run the tear down test last), but for the wrong reason.

**Comment by fasaxc** [comment]
I'd put it at a P2: it's wrong and it could cause confusing hard to understand failures later but it's not causing any immediate harm.

**Comment by fasaxc** [comment]
@doublek you wrote these tests, would you be able to fix them up at some point?
