### ISSUE TITLE
Order table output row

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#75]
The get command does not order the table output for the results.  We should consider adding a sort column or columns.

May not be easy to do with the template engine - so may need to reconsider how we output the tables.

**Comment by robbrockbank** [comment]
I would probably just re-implement the tab writer so that it can handle ordering based on the contents of the columns (in column order)

**Comment by caseydavenport** [comment]
This is actually a calicoctl issue.
