### ISSUE TITLE
Make ipam blockSize configurable

### ISSUE THREAD

**Issue by mdianjun** [projectcalico/libcalico-go#761]
Calico use one "/26" subnet of ipPool  in single node，but in our environment it's too large。
This couldn't be configured, it is hard code as follows: 
```
const (
	blockSize = 64
)

type ipVersion struct {
	Number            int
	TotalBits         int
	BlockPrefixLength int
	BlockPrefixMask   net.IPMask
}

var ipv4 ipVersion = ipVersion{
	Number:            4,
	TotalBits:         32,
	BlockPrefixLength: 26,
	BlockPrefixMask:   net.CIDRMask(26, 32),
}
```

**Comment by caseydavenport** [comment]
Yeah, we've considered this before.

It should be possible, but the IPAM code does assume the block size doesn't change, so we'd need a way to make sure that once set it can't be changed while there are live allocations, and we'd need to make sure all nodes see the same block size.

**Comment by ravilr** [comment]
@caseydavenport the documentation can cover that concern about not changing it in a running cluster right? In our setup, we don't expect to run more than 30 pods per node, so would be helpful to configure this to /27.

**Comment by caseydavenport** [comment]
@ravilr docs for sure, but I'd also like a way to keep people from shooting themselves in the foot accidentally.

I'd definitely like to see this happen, but first need to decide on a config model, etc.

**Comment by karstensi** [comment]
I am interested in this as well, it seems that having kubernetes clusters that can reach the max available pods (100 since k8s v1.2) on a node is not possible when using calico cni, when blockSize is fixed to 64.
https://kubernetes.io/docs/admin/cluster-large/

**Comment by caseydavenport** [comment]
@karstensi Calico's IPAM supports > 64 pods on a node today. Once the 65th IP is requested, a new /26 block will be assigned to that node.

I do think it's still desirable to have this configurable at install time though.

**Comment by karstensi** [comment]
ok that is good to know - thank you.

**Comment by ivan-gusev** [comment]
Maybe make block size part of IPPool metadata? Calicoctl can then prohibit changes of blocksize. In our use case there is "default" IP pool which is happy with /26 block size and bunch of application specific IP pools. For application specific IPPool we dont expect to run more than handful of pods per node so /26 is a lot of waste.

**Comment by caseydavenport** [comment]
This has been merged in https://github.com/projectcalico/libcalico-go/pull/931 and is targeting Calico v3.3.0.
