### ISSUE TITLE
There should be no explicit panic() calls in this library

### ISSUE THREAD

**Issue by redbaron** [projectcalico/libcalico-go#772]
This is somewhat related to https://github.com/projectcalico/libcalico-go/issues/770, libcalico-go being at the core of calico node should never be panicing. If it ever panics, whole  calico mesh goes down without a chance of recovery, since cause of panic would likely be processes again and again.

**Comment by caseydavenport** [comment]
Only one left after this: https://github.com/projectcalico/libcalico-go/pull/789/files

```
lib/ipam/ipam_block.go:         log.Panicf("IP %s not in block %s", ip, b.CIDR)
```

@ozdanborne say's he'll knock that one off too :)
