### ISSUE TITLE
IPAM can give same affinity to multiple hosts

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/libcalico-go#778]
The IPAM affinity claiming process looks like this:

- pre-create the affinity
- try to claim the block
  - on success, return
  - on failure, try to delete the affinity (*)

If the cleanup on failure fails, it looks like we leave the datastore with an affinity that doesn't belong to the host.  

When using an affinity, it doesn't appear that we check that the block actually matches this host.

Presumably, there's also a race where another process on the host tries to use the affinity after the pre-create but before the block has actually been claimed.

## Expected Behavior

- Only one host should be able to claim an affinity.
- (When doing an affine alloc) IPs should only be allocated from blocks that really are owned by this host.

## Current Behavior

- Multiple hosts can claim an affinity.
- IPs can be allocated by all hosts who think they own the block.

## Possible Solution

- Mark the affinity as pending on creation.
- If a host sees a pending affinity when claiming an IP, check whether the block has really been claimed already.
  - if yes, update the affinity
  - if no, try to claim the block and delete affinity on failure.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* libcalico-go version:
* Operating System and version:
* Link to your project (optional):

**Comment by CharlieR-o-o-t** [comment]
Got the same
`
time="2018-02-16T15:44:31Z" level=info msg="Assigning IP 192.168.1.155 to host: xxxx"
time="2018-02-16T15:44:31Z" level=info msg="Host xxxx claiming block affinity for 192.168.1.128/26"
time="2018-02-16T15:44:31Z" level=info msg="Claimed new block: 192.168.1.128/26"
`

**Comment by caseydavenport** [comment]
@CharlieR-o-o-t that shows the host claimed the affinity - do you happen to have logs showing that the affinity is claimed by multiple hosts?

**Comment by feellifexp** [comment]
Does this bug affect v3.0 only or v2.6 is also affected?

**Comment by caseydavenport** [comment]
@feellifexp as far as we know this bug affects both v2.6 and v3.0 (and likely earlier releases as well).

It should be a pretty uncommon occurrence but please let us know if you think you've hit it. I have a PR with a fix here: #785
