### ISSUE TITLE
"make clean && make all" fails due to deepcopy gen

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/libcalico-go#795]
I'm running `make clean && make all` and my builds are failing because `make clean` removes the deepcopy boilerplate code, but none of the other steps (`all`, `test`) recreate the deepcopy code.

## Expected Behavior

`make` should succeed after `make clean`.

## Current Behavior

`make` fails after `make clean`.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* libcalico-go version:
* Operating System and version:
* Link to your project (optional):

**Comment by ozdanborne** [comment]
cc: @bcreane

**Comment by bcreane** [comment]
fixed in libcalico-go `master`. 

@ozdanborne - should this fix get back ported to v3.0 / v2.0 branches?

**Comment by caseydavenport** [comment]
@bcreane if you could open up cherry-picks against those branches that would be great.

**Comment by bcreane** [comment]
This PR isn't relevant to v2.6.
