### ISSUE TITLE
"make test" fails unless you explicitly "make run-etcd && make run-kubernetes-master" first.

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/libcalico-go#798]
`make test` doesn't run etcd for you and fails unless you start etcd with `make run-etcd` and `make run-kubernetes-master` explicitly first. Is this intentional?

## Expected Behavior

running `make test` should pass on a fresh system.

## Current Behavior

`make test` fails on a fresh system.

## Possible Solution

Have `make test` depend on the `run-etcd` target and the `run-kubernetes-master` target.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* libcalico-go version:
* Operating System and version:
* Link to your project (optional):

**Comment by tomdee** [comment]
I fixed this
