### ISSUE TITLE
Add docker container management to calicoctl

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#86]
Add the equivalent of the python calicoctl `calicoctl container` commands.

**Comment by caseydavenport** [comment]
I don't think this should be GA (if we even actually want to do this at all)

**Comment by robbrockbank** [comment]
Indeed.  This should not be GA.

At the moment our plan is to retire this function - it was primarily added to handle container networking prior to CNI and libnetwork.

**Comment by robbrockbank** [comment]
Our current plan is to retire this, so closing out the issue.  If we find we need to re-introduce it we can re-open the issue.
