### ISSUE TITLE
Add node start/stop to calicoctl

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#88]

**Comment by caseydavenport** [comment]
Is this a duplicate of #86 ?

**Comment by robbrockbank** [comment]
@caseydavenport :  Nope, #86 refers to the `calicoctl container` commands

**Comment by caseydavenport** [comment]
Is this really GA for `calicoctl`?  Can we cut this?

**Comment by caseydavenport** [comment]
@robbrockbank I think this doesn't belong in this repo anymore, yeah? :)

Also, any thoughts on the comment above?

**Comment by robbrockbank** [comment]
Yes we can cut since for GA we can (and have to) document running the container.

**Comment by robbrockbank** [comment]
Actually we did implement this for beta.
