### ISSUE TITLE
calico-felix build failed

### ISSUE THREAD

**Issue by peiqi-caicloud** [projectcalico/libcalico-go#899]
Hello, I am trying to build Felix manually to better control our network.
but I met a pb: 

<img width="1440" alt="screen shot 2018-07-02 at 9 35 19 pm" src="https://user-images.githubusercontent.com/5621794/42167249-0852363a-7e40-11e8-8726-f4aaa2ccd289.png">

is it because the libcalico-go version is too old ? or do you have some suggestions

**Comment by caseydavenport** [comment]
@peiqi-caicloud is this a master build? Have you made changes to libcalico or Felix?

**Comment by peiqi-caicloud** [comment]
@caseydavenport 

Hello, 

my cni-plugin and Felix version : release-v3.1. my lib calico-go version is 6b28e7cc060a90b5a96582b03cf42521abc39347. as noted in glide.yaml

I found in my k8s.io/apimachinery/pkg/runtime/scheme.go, there is only AddGeneratedConversionFuncs. no scheme. AddGeneratedDeepCopyFuncs. I found no AddGeneratedConversionFuncs in every different version of apimachinery lib.
my apimachinery version is release-1.8 as noted in glide.yaml of libcalico-go

l am wondering how could I regenerate the zz_generated_deepcopy.go file, and if it can produce the good one version

**Comment by peiqi-caicloud** [comment]
I made no changes to Felix at this moment.

**Comment by caseydavenport** [comment]
@peiqi-caicloud what command did you run to build this?

**Comment by peiqi-caicloud** [comment]
go build in the dir cmd/calico-felix

**Comment by peiqi-caicloud** [comment]
@caseydavenport

**Comment by caseydavenport** [comment]
@peiqi-caicloud that's likely why - I don't believe that's a supported operation at the moment.

You should use the Makefile targets for building Felix.https://github.com/projectcalico/felix/blob/master/Makefile#L45-L52

Simply typing `make` in the project root should do it.
