### ISSUE TITLE
Hard to diagnose if when health checks fail

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/libcalico-go#973]
The health aggregator is quite chatty about the current state, logging `summary=&health.HealthReport{Live:false, Ready:false}` whenever the health is queried.  However, it doesn't log which component is reporting unhealthly.

## Expected Behavior

Think the ideal behaviour would be:

- Always log any unhealthy components when the status is calculated.
- Only log the status itself if it has changed since the last calculation.

## Current Behavior

- Status is logged but per-component status is only logged at debug level.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* libcalico-go version: 
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
We get _some_ output from `kubectl describe`, but for Felix that output is typically just "It failed" (the BIRD output is usually much more detailed and useful to the user).

Felix usually spits out something like this:
```
  Warning  Unhealthy              10s   kubelet, casey-crc-kadm-ms  Readiness probe failed: calico/node is not ready: felix is not ready: readiness probe reporting 503
```

It would be awesome if we could expose this sort of information through kubectl describe as well as part of this.
