### ISSUE TITLE
how to config ips of tunl0? I run calico in k8s, pods ip are assigned before config calico.but some ips would occupied by tunl0.

### ISSUE THREAD

**Issue by zjcbit** [projectcalico/libcalico-go#981]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* libcalico-go version:
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
For future issues, please fill out the issue template.

Calico automatically assigns IP addresses to the tunl0 interfaces on each node, that is expected. They should be from the same IP range as Kubernetes pods.

host networked pods use the IP addresses of the host they are running on.

**Comment by zjcbit** [comment]
> For future issues, please fill out the issue template.
> 
> Calico automatically assigns IP addresses to the tunl0 interfaces on each node, that is expected. They should be from the same IP range as Kubernetes pods.
> 
> host networked pods use the IP addresses of the host they are running on.

Can I assign ips(range as Kubernetes pods) for tunl0? instead of assign ips automatically？

**Comment by caseydavenport** [comment]
You might be able to using the node resource: https://docs.projectcalico.org/v3.3/reference/calicoctl/resources/node

Not sure I understand why you'd want to though.

**Comment by latteczy** [comment]
hi @caseydavenport . Is there a way to get the ip of tunl0?
