### ISSUE TITLE
IPAM Block does not protect against duplicates in Unallocated list

### ISSUE THREAD

**Issue by jsok** [projectcalico/libcalico-go#989]
[`AllocationBlock`](https://github.com/projectcalico/libcalico-go/blob/release-v3.4/lib/backend/model/block.go#L91) is a simple list and the code always assumes the values are unique.

## Expected Behavior

1. An assigned IP should not be assigned twice!
1. Whenever releasing IPs, the supplied list of IPs should be de-duped and handled defensively.

## Current Behavior

`IPAM.ReleaseIPs()` happily accepts a list of IPs that contains duplicates. This will leave duplicates in `Unallocated` which then creates more havoc, in particular **assigning already assigned IPs**.

Reproduced the behaviour in an e2e test: https://github.com/projectcalico/libcalico-go/pull/990

## Possible Solution

Validate ReleaseIPs input and also add checks to [`ipam_block.go`'s `release()` function](https://github.com/projectcalico/libcalico-go/blob/release-v3.4/lib/ipam/ipam_block.go#L203-L206) to stop duplicates being added. Ideally use `lib/set` to avoid bugs like this occurring again.

## Steps to Reproduce (for bugs)

Call `ReleaseIPs([]cnet.IP{ip, ip}` with a duplicate entry in the list, then keeping assigning IPs and you will eventually get `ip` assigned twice.

Have now observed multiple instances of doubly-assigned IPs in running production cluster.

Doing a quick audit reveals an IP block with duplicates in the unallocated list, but have observed other IP pools with the same issue:

```
for subnet in $(etcdctl ls --sort /calico/ipam/v2/assignment/ipv4/block)
do
    etcdctl get $subnet | jq 'if (.unallocated | length) != (.unallocated | unique | length) then "duplicate found \(.cidr)" else empty end'
done
```

## Context

A running container has it's IP assigned to another container. Whichever exits first will release that IP leaving the other with an IP that's been released. Rinse-and-repeat.

## Your Environment

Calico 2.6.12, running Docker with libnetwork on Mesos.

* libcalico-go version: 1.7.3
* Operating System and version: Ubuntu 18.04 bionic
* Link to your project (optional):

**Comment by jsok** [comment]
@caseydavenport happy to work on a fix if you have any guidance, otherwise I have a solution I can suggest via PR?

**Comment by caseydavenport** [comment]
@jsok sounds like something reasonable to fix. The one thing I'm not sure on is how we're hitting this - which code is calling ReleaseIPs with duplicate entries? That feels like it could be a result of another bug elsewhere in the code?

**Comment by jsok** [comment]
I've repurposed https://github.com/projectcalico/libcalico-go/pull/990 to act as a fix for this issue.

**Comment by stephanh** [comment]
@caseydavenport any update on this issue? Is it possible to get #990 reviewed? This issue has hit us quite hard again today.

**Comment by caseydavenport** [comment]
Sorry for the delay, I will try to review this week.

I'm still not sure how we're hitting this, though. I worry there is a bug higher up in the call stack which is causing this scenario to get hit. What might be calling release with duplicate IPs?

**Comment by jsok** [comment]
@caseydavenport yes I’m stumped as to how this is triggering in my cluster. The etcdctl / jq snippet in the Issue description definitely and regularly trips up duplicates in the list.

Looking at libnetwork I can’t see how it could be constructing a release request with duplicate IPs...
